### ISSUE TITLE
SSC license not found on silver lexus

### ISSUE THREAD

**Issue by adev4a** [usdot-fhwa-stol/carma-platform#2002]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

While testing on the silver lexus it was found that the ssc autoware node crashes with a warning for the ssc license not being found on the system.
Checking vehicle/calibration shows that the file exists on the system. This was tested on develop and release/isetta and had the same error thrown for both.
The mentioned error does not make carma-platform crash but stops the vehicle from moving when engaged. 

### Carma version where this issue was discovered

Release candidate- isetta and develop.

### Expected behavior
ssc driver node starts up without issue and the vehicle moves when carma is engaged.

### Actual behavior

Vehicle does not move when carma is engaged.
### Steps to reproduce the actual behavior

1.Set the silver lexus to run develop or release/isetta.
2. Start up carma and monitor terminal for ssc container startup logs.
3. Select a route and Engage the vehicle.

**Comment by msmcconnell** [comment]
This issue appears to have been caused by a change in the Environment variable handling in ros2 launch. 
In this release
https://github.com/ros2/ros2/releases/tag/release-foxy-20221021
https://discourse.ros.org/t/new-packages-and-patch-release-for-foxy-fitzroy-2022-10-21/27883

Notably:
"This fixes two regressions in ros2/launch and ros2/rclpy caught in the previous build. See [Fix the restoring of os.environ to maintain type ros2/launch #662](https://github.com/ros2/launch/pull/662) and [Revert "Raise user handler exception in MultiThreadedExecutor ros2/rclpy #1017 1](https://github.com/ros2/rclpy/pull/1021) for details."

A number of changes were made to the environment variable handling in ROS2 launch. Why exactly we didn't see the issue until January when our images were built in early December is unclear. It's also not clear what exactly our launch files are doing wrong now since a basic SetEnvironmentVariable in a GroupAction is all that is occurring. 


We have worked around the issue in an acceptable way with the above 2 PRs
