### ISSUE TITLE
NAS data storage folder not available on Black Pacifica due to hardware issue.

### ISSUE THREAD

**Issue by snallamothu** [usdot-fhwa-stol/carma-platform#799]
![20200731_101558](https://user-images.githubusercontent.com/3028188/89322727-aad57680-d652-11ea-8869-6e216f431767.jpg)
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The NAS data storage server on the Black Pacifica doesn't recognize the hard drives any more, it reports that drives are in "unconfigured bad" state at startup.  So, data cannot be written to the shared folder.
### Expected behavior
CARMA can log to the NAS.

### Software version this applies to
v 3.3.0 but this a hardware issue.

### Actual behavior
See description

### Steps to reproduce the behavior

1. Reboot server
2. Press delete when prompted to enter the setup utility
3. Browse to Advanced tab and click on hardware drive status.

### Related work
N/A

**Comment by TonysCousin** [comment]
Marking this severity 3, as Carma can be fully functional with the NAS detached.  We are simply limited in the amount of testing that can be done between log deletions.

**Comment by jtbaird** [comment]
RAID0 groups hard drives into virtual drives, and writes data across all of them simultaneously. Because of this, if one drive gets removed, the virtual drive is now broken, and all hard drives associated with it will show up as "unconfigured bad." The solution is to remove all the hard drives, put them in the IS300 server, go to the boot menu > MegaRIAD menu > drive management and then rebuild the drives.

In the future this can be prevented by removing/installing all of a virtual drive's hard drives simultaneously.
